### ISSUE TITLE
Missing dependency dev-python/ciso8601 in app-misc/homeassistant-0.108.3-r1

### ISSUE THREAD

**Issue by zhtengw** [onkelbeh/HomeAssistantRepository#12]
Update homeassistant to 0.108.3-r1 but it crashed when start.
/var/log/homeassistant/server.log shows
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/hass", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ciso8601==2.1.3' distribution was not found and is required by homeassistant
```

After emerge dev-python/ciso8601, HA works. So dev-python/ciso8601 should be added to the "RDEPEND" of homeassistant.

**Comment by onkelbeh** [comment]
Thalns for the feedback, it's listed in core dependencies. Have this installed on both boxes, don't remember where it came from. Intend to do a full compile from scratch test soon, perhaps with 0.108.6 and clean this up a bit more.

**Comment by onkelbeh** [comment]
Hi @zhtengw,

this is growing i bit bigger, I have to rework the complete core requirements, which have grown over the last years without any structure. Looks to me that some crap is hiding there. This will take some more days. I am doing [some experiments](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/f087f166aa7cd18c297f921247a473203ffe58e0). If you want to take a look, the mess is in the 4th dependency block. I am still searching for a way to retrace where these all came from.

**Comment by onkelbeh** [comment]
Better look in https://git.edevau.net/onkelbeh/HomeAssistantRepository/src/branch/master/app-misc/homeassistant/homeassistant-0.108.5-r1.ebuild, could be it will change during cleanup.

**Comment by onkelbeh** [comment]
Should be fixed in https://github.com/onkelbeh/HomeAssistantRepository/releases/tag/v0.108.9,
further dependency cleanup in main Ebuild will continue.
