### ISSUE TITLE
Setup failed for ssdp: Unable to import component: No module named 'async_upnp_client.server'

### ISSUE THREAD

**Issue by undrwater** [onkelbeh/HomeAssistantRepository#207]
Home Assistant version: app-misc/homeassistant-2023.1.2

Issues:
Integrations (Hue, Brother) broken due to the above. Clicking "Add Integration" results in a never ending spinning circle.

Logs:
[logs](https://bpa.st/7CVFS)

**Comment by onkelbeh** [comment]
just to keep the logs:

```
2023-01-10 13:31:32.121 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-10 13:31:33.637 ERROR (MainThread) [homeassistant.setup] Setup failed for ssdp: Unable to import component: No module named 'async_upnp_client.server'
2023-01-10 13:31:33.809 ERROR (MainThread) [homeassistant.setup] Setup failed for bluetooth: Unable to import component: cannot import name 'BleakSlotManager' from 'bleak_retry_connector' (/etc/homeassistant/deps/lib/python3.10/site-packages/bleak_retry_connector/__init__.py)
2023-01-10 13:31:34.353 ERROR (MainThread) [homeassistant.setup] Setup failed for country: Integration not found.
2023-01-10 13:31:34.380 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of upnp. Setup failed for dependencies: ssdp
2023-01-10 13:31:34.382 ERROR (MainThread) [homeassistant.setup] Setup failed for upnp: (DependencyError(...), 'Could not setup dependencies: ssdp')
2023-01-10 13:31:35.693 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration hue to set up hue configuration entry: No module named 'async_upnp_client.server'
2023-01-10 13:31:40.566 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of default_config. Setup failed for dependencies: bluetooth, ssdp
2023-01-10 13:31:40.568 ERROR (MainThread) [homeassistant.setup] Setup failed for default_config: (DependencyError(...), 'Could not setup dependencies: bluetooth, ssdp')
2023-01-10 13:31:42.409 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration brother: cannot import name 'BrotherSensors' from 'brother' (/etc/homeassistant/deps/lib/python3.10/site-packages/brother/__init__.py)
2023-01-10 13:31:42.664 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 850, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/lib/python3.10/site-packages/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/lib/python3.10/site-packages/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/homeassistant/components/brother/__init__.py", line 8, in <module>
    from brother import Brother, BrotherSensors, SnmpError, UnsupportedModel
ImportError: cannot import name 'BrotherSensors' from 'brother' (/etc/homeassistant/deps/lib/python3.10/site-packages/brother/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/helpers/discovery_flow.py", line 71, in _async_start
    await gather_with_concurrency(
  File "/usr/lib/python3.10/site-packages/homeassistant/util/async_.py", line 203, in gather_with_concurrency
    return await gather(
  File "/usr/lib/python3.10/site-packages/homeassistant/util/async_.py", line 201, in sem_task
    return await task
  File "/usr/lib/python3.10/site-packages/homeassistant/data_entry_flow.py", line 229, in async_init
    flow, result = await task
  File "/usr/lib/python3.10/site-packages/homeassistant/data_entry_flow.py", line 247, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 857, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2023-01-10 13:31:42.731 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration hue: No module named 'async_upnp_client.server'
```
